server:
  port: 8091

spring:
  redis:
    host: 127.0.0.1

milkomeda:
  # 配置是否显示跟踪日志信息（线上环境应该关闭）
  show-log: true

  echo:
    # 设置请求读取超时
    read-timeout: 10000

  crust:
    # 使用对称密钥生成token
    secure-key: crust_secure_key
    # 自定义token头，默认为token
    token-name: Authorization
    # 不使用BCrypt（如果用户表有salt字段的情况）
#    use-bCrypt: false
