server:
  port: 8091

spring:
  redis:
    host: 127.0.0.1

milkomeda:
  # 配置是否显示跟踪日志信息（线上环境应该关闭）
  show-log: true

  echo:
    # 设置请求读取超时
    read-timeout: 10000

  crust:
    # 使用对称密钥生成token
    secure-key: crust_secure_key
    # 自定义token头，默认为token
    token-name: Authorization
    # 不使用BCrypt（如果用户表有salt字段的情况）
#    use-bCrypt: false

  ice:
    # 开启Job作业（默认为true，仅作为消费端使用时，设置false）
#    enable-job-timer: false
    # 延迟队列分桶数量（默认为3）
    delay-bucket-count: 2
    # 消费执行超时时间（默认5000ms）
    ttr: 10000
    # 重试时添加延迟增长因子（默认为1，计算公式：delay * (retryCount++) * factor）
    retry-delay-multi-factor: 2
    # 开启Task功能，开发者就可以通过注解方式接收topic消息（如果是微服务布署服务端方案时，保持默认false)
    enable-task: true
    # 最大消费个数（默认为10）
    task-topic-pop-max-size: 5
    # 消费轮询间隔（默认5000ms）
    task-execute-rate: 2000
